useTabs = true
singleQuote = true
trailingComma = "none"
printWidth = 100
overrides = [{ files = "*.svelte", options = { parser = "svelte" } }]

plugins = [
  "prettier-plugin-organize-attributes",
  "prettier-plugin-tailwindcss",
  "prettier-plugin-svelte",
]

attributeSort = "ASC"
